apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: dts-postgres
  name: dts-postgres-init-sql
  namespace: dts-test
data:
  pooler_application.sql: |
    GRANT CONNECT ON DATABASE dts_edison TO cnpg_pooler_pgbouncer;
    CREATE OR REPLACE FUNCTION public.user_search(uname TEXT)
      RETURNS TABLE (usename name, passwd text)
      LANGUAGE sql SECURITY DEFINER AS
      'SELECT usename, passwd FROM pg_catalog.pg_shadow WHERE usename=$1;';
    REVOKE ALL ON FUNCTION public.user_search(text) FROM public;
    GRANT EXECUTE ON FUNCTION public.user_search (text) TO cnpg_pooler_pgbouncer;
  pooler_postgres.sql: |
    CREATE ROLE cnpg_pooler_pgbouncer WITH LOGIN;
