apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  labels:
    app.kubernetes.io/name: dts-postgres
  name: dts-postgres-pooler-rw
  namespace: dts-test
spec:
  cluster:
    name: dts-postgres
  deploymentStrategy:
    type: RollingUpdate
  instances: 2
  pgbouncer:
    authQuery: SELECT usename, passwd FROM public.user_search($1)
    authQuerySecret:
      name: dts-postgres-pooler
    parameters:
      default_pool_size: "10"
      ignore_startup_parameters: search_path
      max_client_conn: "80"
    poolMode: session
  serviceTemplate:
    metadata:
      labels:
        app.kubernetes.io/name: dts-postgres
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dts-postgres
    spec:
      containers:
        - image: ghcr.io/cloudnative-pg/pgbouncer:1.24.1
          name: pgbouncer
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/name: dts-postgres
              cnpg.io/podRole: pooler
              cnpg.io/poolerName: dts-postgres-pooler-rw
          matchLabelKeys:
            - pod-template-hash
          maxSkew: 1
          topologyKey: topology.kubernetes.io/region
          whenUnsatisfiable: ScheduleAnyway
        - labelSelector:
            matchLabels:
              app.kubernetes.io/name: dts-postgres
              cnpg.io/podRole: pooler
          matchLabelKeys:
            - pod-template-hash
          maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
  type: rw
