apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: k8s-pki
  namespace: cert-manager
spec:
  isCA: true
  commonName: k8s kind PKI Authority
  duration: 2160h0m0s
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  privateKey:
    algorithm: ECDSA
    rotationPolicy: Always
    size: 384
  secretName: k8s-pki-ca
